### ISSUE TITLE
Champion's Path code should be CPA

### ISSUE THREAD

**Issue by lfgcampos** [kirbyUK/ptcgo-data#1]
According to the info from the API and pkmncards, the code should be CPA and not CP.

https://pkmncards.com/set/champions-path/
https://api.pokemontcg.io/v1/sets?name=Champions%20Path

**Comment by kirbyUK** [comment]
Are you sure it shouldn't be `swsh35`? My data only has the `setCode` field, not the PTCGO code.

**Comment by kirbyUK** [comment]
I've renamed to `swsh35` and closed, feel free to reopen if you think I've got it wrong. Otherwise, thank you for reporting! :)

**Comment by lfgcampos** [comment]
The json itself could be `cpa.json` but `swsh35` works as well
