### ISSUE TITLE
Vivid Voltage (SWSH4)

### ISSUE THREAD

**Issue by lfgcampos** [kirbyUK/ptcgo-data#2]
Not sure if this is already available but the release date is tomorrow (2020-11-13).

**Comment by kirbyUK** [comment]
For future reference, the data doesn't go live until the day of release.

Thanks for reminding me though! I don't follow the game anymore, so I don't actually know when the sets are coming out

**Comment by lfgcampos** [comment]
I noticed that sometimes you were able to get it before the release date... but since the release was today, I just opened the issue yesterday =)
